  #sudo: required

  os: linux

  # 언어(플랫폼)선택
  language: generic

  # ----------------------------
  # *** 우분투 릴리즈별 코드명  ***
  # Xenial Xerus (16.04)
  # Yakkety Yak (16.10)
  # Zesty Zapus (17.04)
  # Artful Aardvark (17.10)
  # Bionic Beaver (18.04)
  # ----------------------------
  dist: bionic

  services:
    - docker
  
  before_install:
    - echo "start creating an image with dockerfile"
    - docker build -t syacooms/docker-react-app -f Dockerfile.dev .

  script:
    - docker run -e CI=true syacooms/docker-react-app npm run test -- --coverage

  # provider : 외부 서비스 표시
  # region : 현재 사용하고 있는 aws의 물리적 장소
  # app : 생성된 어플리케이션의 이름
  # env : app-env (env 이름 지정 안했을 시)
  # bucket_name : 해당 elasticbeanstalk을 위한 버켓 이름 fixed bucket
  # bucket_path : app 이름
  # branch : travis.yml에서 테스트/배포할 branch
  # access_key_id : IAM에서 ROOT 사용자가 권한을 준 USER의 KEY travis.org setting에도 등록
  # secret_access_key : 동일

  deploy:
    provider: elasticbeanstalk
    region: "ap-northeast-2"
    app: "docker-react-app"
    env: "DockerReactApp-env"
    bucket: "elasticbeanstalk-ap-northeast-2-285164948650"
    bucket_path: "docker-react-app"
    on:
      branch: master

    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_ACCESS_KEY